install ack
install curl
install fzf
install git
install hub
install neovim
install neovim-dot-app
install the_silver_searcher
install tldr
install wget
install z
tap homebrew/dupes
tap josegonzalez/homebrew-php
install php70
install php70-xdebug
install php70-mcrypt
doctor
